# New trip states
TRIP_COMPANY = 1
TRIP_ROUTE = 2
TRIP_DATE = 3
TRIP_SEATS = 4
TRIP_PRICE = 5
TRIP_CONFIRM = 6

# Edit trip states
TRIP_EDIT_MENU = 10
TRIP_EDIT_FIELD = 11

# Archive states
ARCHIVE_CONFIRM = 15

# New booking states
BOOKING_LINK = 20
BOOKING_CITY = 21
BOOKING_PASSENGERS_COUNT = 22
BOOKING_PASSENGER_NAME = 23
BOOKING_PASSENGER_PHONE = 24
BOOKING_PAID = 25
BOOKING_BALANCE = 26
BOOKING_COMMENT = 27
BOOKING_CONFIRM = 28

# Edit booking states
BOOKING_EDIT_MENU = 30
BOOKING_EDIT_CITY = 31
BOOKING_EDIT_PAID = 32
BOOKING_EDIT_COMMENT = 33
BOOKING_EDIT_LINK = 34
BOOKING_DELETE_CONFIRM = 35

# Search
SEARCH_QUERY = 40

# Stats
STATS_DETAIL = 50
